namespace:
  name: trexflanken

deployment:
  name: trexflankenyoga
  image: ghcr.io/torbencarstens/trexflanken:__TAG__
  imagePullPolicy: IfNotPresent
  revisionHistoryLimit: 1
  replicas: 2
  ports:
  - 8080
  labels:
    app: trexflankenyoga
  requests:
    cpu: 50m
    memory: 10Mi
  limit:
    cpu: 300m
    memory: 50Mi
  healthEndpoint: /health

service:
  name: trexflankenyoga
  port: 80
  targetPort: 8080
  appSelector: trexflankenyoga

ingress:
  secret: tls-trexflankenyoga
  issuer: letsencrypt-issuer
  name: trexflankenyoga
  hosts:
    - name: trexflanken.yoga
