name: Build image

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: OpenAlcoholics/github-action-helm@v0.1.5
        with:
          raw_command: lint
      - uses: OpenAlcoholics/github-action-helm@v0.1.5
        with:
          raw_command: lint --strict
  template:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: OpenAlcoholics/github-action-helm@v0.1.5
        with:
          raw_command: template .
