name: Build and deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  lint:
    name: "helm lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: OpenAlcoholics/github-action-helm@v0.2.0
        with:
          raw_command: lint --strict

  deploy:
    name: "Publish to k8s"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: install helm chart
        uses: OpenAlcoholics/github-action-helm@v0.2.0
        with:
          subcommand: upgrade
          release_name: trexflanken
          ref: .
          namespace: trexflanken
          install: true
          atomic: true
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}